// vehicle reducer related action
export const FETCH_ALL_VEHICLE = 'FETCH_ALL_VEHICLE';
export const FILTER_VEHICLE_LIST = 'FILTER_VEHICLE_LIST';
export const CLEAR_VEHICLE_FILTER_LIST = 'CLEAR_VEHICLE_FILTER_LIST';
export const FILTER_BY_PRICE_VEHICLE = 'FILTER_BY_PRICE_VEHICLE';
export const ERROR_VEHICLE = 'ERROR_VEHICLE';
export const UPDATE_VEHICLE_PAGE_NUMBER = 'UPDATE_PAGE_NUMBER';
export const FILTER_BY_FAVOURITES_VEHICLE = 'FILTER_BY_FAVOURITES_VEHICLE';

// starships reducer related action
export const FETCH_ALL_STARSHIPS = 'FETCH_ALL_STARSHIPS';
export const FILTER_STARSHIPS_LIST = 'FILTER_STARSHIPS_LIST';
export const CLEAR_STARSHIPS_FILTER_LIST = 'CLEAR_STARSHIPS_FILTER_LIST';
export const FILTER_BY_PRICE_STARSHIPS = 'FILTER_BY_PRICE_STARSHIPS';
export const ERROR_STARSHIPS = 'ERROR_STARSHIPS';
export const UPDATE_STARSHIPS_PAGE_NUMBER = 'UPDATE_STARSHIPS_PAGE_NUMBER';
